<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Deterministic>true</Deterministic>
    <DebugType>embedded</DebugType>
    <PathMap Condition="'$(Configuration)' == 'Release'">$(MSBuildThisFileDirectory)=/_/</PathMap>
    <Product>Context Mole</Product>
    <Company>JPCodeCraft</Company>
    <Authors>JPCodeCraft</Authors>
    <Copyright>Copyright (c) 2026 JPCodeCraft</Copyright>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
  </PropertyGroup>
</Project>
